In [2]:
import numpy as np

In [5]:
a = np.ones(2, 4, 8)

TypeError: ignored

In [3]:
import pandas as pd
df = pd.DataFrame({"A" : [0, 2], "B": [1, 3]})
df

A  B
0  0  1
1  2  3

In [6]:
df.to_numpy()

array([[0, 1],
       [2, 3]])

In [17]:
a = np.array([[1, 21, 3], [4, 15, 6], [7, 8, 9]])
a

array([[ 1, 21,  3],
       [ 4, 15,  6],
       [ 7,  8,  9]])

In [18]:
a[1][2]

6

In [19]:
a[0:2, 1:3]

array([[21,  3],
       [15,  6]])

In [20]:
a = a.T
a

array([[ 1,  4,  7],
       [21, 15,  8],
       [ 3,  6,  9]])

In [21]:
a.flatten()

array([ 1,  4,  7, 21, 15,  8,  3,  6,  9])

In [22]:
np.sum(a, axis = 0)

array([25, 25, 24])

In [23]:
np.sum(a)

74

In [24]:
np.linalg.det(a)

-6.000000000000029

In [25]:
b = np.array([[2, 4, 2], [5, 4, 5], [98, 1, 22]])

In [26]:
a+b

array([[  3,   8,   9],
       [ 26,  19,  13],
       [101,   7,  31]])

In [27]:
a-b

array([[ -1,   0,   5],
       [ 16,  11,   3],
       [-95,   5, -13]])

In [29]:
np.cross(a, b)

array([[ -20,   12,   -4],
       [  43,  -65,    9],
       [ 123,  816, -585]])

In [31]:
a*b #element-wise multiplication, not real matrix multiplication

array([[  2,  16,  14],
       [105,  60,  40],
       [294,   6, 198]])

In [30]:
np.multiply(a, b) #element-wise multiplication, not real matrix multiplication

array([[  2,  16,  14],
       [105,  60,  40],
       [294,   6, 198]])

In [32]:
np.dot(a, b) #true matrix multiplication, as in rows from the first matrix * columns of the second

array([[708,  27, 176],
       [901, 152, 293],
       [918,  45, 234]])

In [35]:
np.zeros((1, 224, 224, 3)) + 3 #broadcasting

array([[[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        ...,

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.],
         ...,
         [3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]]])

In [36]:
a

array([[ 1,  4,  7],
       [21, 15,  8],
       [ 3,  6,  9]])

In [37]:
a + np.array([2, 3, 5]) #This is also Broadcasting

array([[ 3,  7, 12],
       [23, 18, 13],
       [ 5,  9, 14]])

In [38]:
a.ndim

2

In [39]:
c = np.ones((3, 4, 2))
c.ndim

3

In [51]:
a = np.array([[ 1,  4,  7],
       [21, 15,  8], [4, 0, 43],
       [ 3,  6,  9]])

In [52]:
a.shape[1] #The feature vectors themselves have dimensions: the number of features (So a row like [34, 0, 1, 5.5] would be a 4 dimensional vector)

3

In [53]:
a.shape 

(4, 3)

In [54]:
a.size

12

In [55]:
print(np.amin(a))
print(np.amax(a))

0
43


In [59]:
np.where(a == 4)

(array([0, 2]), array([1, 0]))

In [60]:
np.save("name.npy", a)

In [61]:
new_arr = np.load("name.npy")
new_arr

array([[ 1,  4,  7],
       [21, 15,  8],
       [ 4,  0, 43],
       [ 3,  6,  9]])