In [ ]:
import numpy as np
theta = np.array([0, 0])
theta_not = 0

In [ ]:
theta += (2, -1)
theta_not += 1
theta, theta_not

(array([ 2, -1]), 1)

In [ ]:
-1 * (theta.T.dot([-1, -3]) + theta_not) <= 0

True

In [ ]:
theta += (-1, -3)
theta_not += -1
theta, theta_not

(array([ 1, -4]), 0)

In [ ]:
-1 * (theta.T.dot([0, 4]) + theta_not) <= 0

False

In [ ]:
1 * (theta.T.dot([2, -1]) + theta_not) <= 0

False

In [ ]:
-1 * (theta.T.dot([-1, -3]) + theta_not) <= 0

True

In [ ]:
theta += (-1, -3)
theta_not += -1
theta, theta_not

(array([ 0, -7]), -1)

In [ ]:
-1 * (theta.T.dot([0, 4]) + theta_not) <= 0

False

In [ ]:
1 * (theta.T.dot([2, -1]) + theta_not) <= 0

False

In [ ]:
-1 * (theta.T.dot([-1, -3]) + theta_not) <= 0

True

In [ ]:
theta += (-1, -3)
theta_not += -1
theta, theta_not

(array([ -1, -10]), -2)

In [ ]:
-1 * (theta.T.dot([0, 4]) + theta_not) <= 0

False

In [ ]:
1 * (theta.T.dot([2, -1]) + theta_not) <= 0

False

In [ ]:
-1 * (theta.T.dot([-1, -3]) + theta_not) <= 0

True

In [ ]:
theta += (-1, -3)
theta_not += -1
theta, theta_not

(array([ -2, -13]), -3)

In [ ]:
-1 * (theta.T.dot([0, 4]) + theta_not) <= 0

False

In [ ]:
1 * (theta.T.dot([2, -1]) + theta_not) <= 0

False

In [ ]:
-1 * (theta.T.dot([-1, -3]) + theta_not) <= 0

True

In [ ]:
theta += (-1, -3)
theta_not += -1
theta, theta_not

(array([ -3, -16]), -4)